apiVersion: v1
kind: Service
metadata:
  name: rocket-server-svc
spec:
  type: ClusterIP
  selector:
    app: rocket-server
  ports:
    - name: http
      protocol: TCP
      port: 2345
      targetPort: 8000
